name: BlockToHead
version: '${project.version}'
main: com.trassert.blockOnHead.BlockOnHead
api-version: '1.17'
folia-supported: true

description: Allows players to put blocks and items on their heads.

commands:
  onhead:
    description: Put the item in your main hand on your head.
    usage: /onhead
    permission: lumintohead.use

  onheadreload:
    description: Reload BlockToHead configuration.
    usage: /onheadreload
    permission: lumintohead.reload

permissions:
  lumintohead.use:
    description: Allows using /onhead.
    default: true

  lumintohead.reload:
    description: Allows reloading the plugin configuration.
    default: op

  lumintohead.bypass:
    description: Allows wearing items that are not in the whitelist.
    default: op